# Site settings
name: Mahinoor Ekram
avatar: images/cropped_image.png

# Contact / social links
footer-links:
  email: ekramahinoor@gmail.com
  linkedin: https://www.linkedin.com/in/mahinoorekram/
  pinterest: null
  rss: null
  twitter: null
  stackoverflow: null
  youtube: null
  googleplus: null

# Disqus & Google Analytics
disqus: null
google_analytics: null

# Site URL (GitHub Pages)
url: "https://ekramahinoor.github.io"
baseurl: ""  # since this is a user site, no baseurl needed

# Permalink
permalink: /

# Jekyll version
version: v1.2.0

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass settings
sass:
  style: :compressed

# Plugins
plugins:
  - jekyll-sitemap
  # - jekyll-feed

# Files to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - command.txt
  - todo.txt
  - _temp/index.html
  - _temp/
